### Import libraries
```{r}
library(pacman)
pacman::p_load(tidyverse, ggplot2, emmeans, sandwich, lmtest)
options(scipen = 999)
```

### Combine all data saving information on genres and seed
```{r}
read_bias_data <- function(genre, seed) {
  file <- glue::glue("data/associational_gender_bias/{genre}_{seed}_associational_gender_bias.csv")
  read_csv(file)
}

genres <- c("romance", "sci_fi", "literary_fiction")
seeds  <- c("2000", "42", "123", "999")

all_data <- expand_grid(genre = genres, seed = seeds) %>%
  mutate(data = map2(genre, seed, read_bias_data))

bias_data_all <- all_data %>%
  unnest(data)

```

```{r}
bias_data_all %>%
  count(genre, seed)
```

### Test data for model assumptions
```{r}
# test for homoscedasticity
bptest(model)  # Breusch-Pagan test, H0 = homoscedasticity
```

```{r}
# test for normaility of gender bias
shapiro.test(bias_data_all$gender_bias) # H0 = data is normally distributed
hist(bias_data_all$gender_bias, col='steelblue') # data looks normal though
```

### Modeling (very much in the testing phase)
```{r}
# Fit model as before
model <- lm(gender_bias ~ 0 + dimension * genre * seed, data = bias_data_all)
# no intercept model to compute means for each dimension × genre × seed combination


# Use robust standard errors in emmeans
emm <- emmeans(model, ~ dimension * genre | seed, # compute dimension × genre means separately for each seed
               vcov. = vcovHC(model, type = "HC3"))# corrects for heteroscedasticity

emm_df <- as.data.frame(emm)

emm_df <- emm_df %>%
  group_by(dimension, genre) %>%
  summarise(
    mean_bias = mean(emmean),
    sd_bias   = sd(emmean),
    lower_CI = mean_bias - 1.96 * sd_bias, # confidence interval for mean bias across seeds
    upper_CI = mean_bias + 1.96 * sd_bias # confidence interval for mean bias across seeds
  )
```

### Attempting to plot mean bias with confidence intervals across seeds (error bars represent variability across seeds, not within seed)
```{r}
# Plot mean ± CI (only plotting error across seeds)
ggplot(emm_df, aes(x = dimension, y = mean_bias, color = dimension)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = lower_CI, ymax = upper_CI), width = 0.2) +
  facet_wrap(~ genre) +
  labs(
    x = "Dimension",
    y = "Mean Gender Bias",
    color = "Dimension",
    title = "Mean Gender Bias Across Dimensions and Genres with 95% CI"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom")
```


